services:
  crafty:
    container_name: crafty_controller
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
      - TZ=Etc/UTC
    ports:
      - "8443:8443" # HTTPS
      - "8123:8123" # DYNMAP
      - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
      - /home/neonvariant/docker/crafty-controller/backups:/crafty/backups
      - /home/neonvariant/docker/crafty-controller/logs:/crafty/logs
      - /home/neonvariant/docker/crafty-controller/servers:/crafty/servers
      - /home/neonvariant/docker/crafty-controller/config:/crafty/app/config
      - /home/neonvariant/docker/crafty-controller/import:/crafty/import
